name: Tests

on:
  push:
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - 3.8
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Red-DiscordBot
      - name: Compile all
        run: |
          make compile
  style:
    name: Style check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - 3.8
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Red-DiscordBot
          python -m pip install black==19.10b0
      - name: Checking style
        run: |
          make stylecheck
